### ISSUE TITLE
model for greyscale images?

### ISSUE THREAD

**Issue by dschneiderch** [Gregor-Mendel-Institute/aradeepopsis#53]
Hi @phue,
the segmentation worked great on the first dataset after I sorted out the docker storage issue. Next I tried to run model A on some greyscale images - is that possible or do the models depend on shape and color differences?
I got this error which wasn't clear to me if it was related and i couldnt find a `.command.sh`

```
Staging foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb                                                                                       WARN: Unable to stage foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb (try 1) -- Cause: Unable to access path: /record/3946618/files/1_class_singlescale.pb                                                                                                                                                              WARN: Unable to stage foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb (try 2) -- Cause: Unable to access path: /record/3946618/files/1_class_singlescale.pb                                                                                                                                                              WARN: Unable to stage foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb (try 3) -- Cause: Unable to access path: /record/3946618/files/1_class_singlescale.pb
Error executing process > 'run_predictions (42)'

Caused by:
  Can't stage file https://zenodo.org/record/3946618/files/1_class_singlescale.pb -- reason: Unable to access path: /record/3946618/files/1_class_singlescale.pb

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

my command
```
nextflow run Gregor-Mendel-Institute/aradeepopsis --images 'data/psII/*.png' -profile docker --shiny false --outdir output/deeposisA-psII --model A
```

**Comment by phue** [comment]
Hi @dschneiderch,

> the segmentation worked great on the first dataset after I sorted out the docker storage issue. Next I tried to run model A on some greyscale images - is that possible or do the models depend on shape and color differences?

The models have been trained on RGB images, so colour information certainly plays a role for the model prediction. I don't think it will work well on singlechannel images.


> I got this error which wasn't clear to me if it was related and i couldnt find a `.command.sh`
> 
> ```
> Staging foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb                                                                                       WARN: Unable to stage foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb (try 1) -- Cause: Unable to access path: /record/3946618/files/1_class_singlescale.pb                                                                                                                                                              WARN: Unable to stage foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb (try 2) -- Cause: Unable to access path: /record/3946618/files/1_class_singlescale.pb                                                                                                                                                              WARN: Unable to stage foreign file: https://zenodo.org/record/3946618/files/1_class_singlescale.pb (try 3) -- Cause: Unable to access path: /record/3946618/files/1_class_singlescale.pb
> Error executing process > 'run_predictions (42)'
> 
> Caused by:
>   Can't stage file https://zenodo.org/record/3946618/files/1_class_singlescale.pb -- reason: Unable to access path: /record/3946618/files/1_class_singlescale.pb
> 
> Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
> ```

The pipeline fetches the pretrained models from this [Zenodo record](https://zenodo.org/record/3946618), which doesn't seem to be very reliable for that purpose. I need to upload them somewhere else and update the pipeline.

In the meantime, you can either try again (it will work eventually) or change back to the dropbox links (see https://github.com/Gregor-Mendel-Institute/aradeepopsis/commit/f7566a0d49cd4f36ab39816aa206368d1ecb4ac7)

**Comment by dschneiderch** [comment]
do you think it would be possible to train a similar model with grayscale images or does imagenet+ rely on color info too?

**Comment by phue** [comment]
It should be possible, although the input layer of the model needs to be changed to work with 1-channel images.

I think the main problem is that the pretrained weights in DeepLabV3+ are obtained by pretraining on the ImageNet dataset which also consists of RGB images.
So I guess if you use that for transfer learning with grayscale images, it is also not optimal (but it might be worth a try)
 
A better way would be to convert the whole ImageNet dataset to grayscale and train on that, but that is probably not feasible because of the hardware requirements that come with it.

**Comment by dschneiderch** [comment]
that was my intuition. do you work with grayscale images? automated segmentation would be 👌
I do a lot of chlorophyll fluorescence imaging and often algae turns up. it can be quite difficult to segment well.
![A1-doi-20200531T210155-PSII0-12](https://user-images.githubusercontent.com/7461221/103921087-ea533380-50c6-11eb-95af-c327d9db0f33.png)

**Comment by phue** [comment]
> do you work with grayscale images? 

No I don't. Fluorescence imaging is an interesting topic, but we currently don't have a camera for that.
