### ISSUE TITLE
Unable to get model using Nextflow

### ISSUE THREAD

**Issue by G-Thomson** [Gregor-Mendel-Institute/aradeepopsis#62]
I am trying to get Aradeepopsis up and running and run into the following error after running the command using a single image that follows the same format as that on the Github README:

```
/nextflow run Gregor-Mendel-Institute/aradeepopsis --images './images/example.jpg' -profile singularity

No such file: https://cdn.vbc.ac.at/clip/reframe/data/aradeepopsis/3_class_singlescale.pb

```

I tried it on a local machine using docker, and my institutions HPC using singularity and got the same error. 
I can download the model from the CDN so I know it is there. 
I might be missing something due to my inexperience with Nextflow but is this an error that has been encountered previously? If so how is it resolved?

Colleagues of mine have the program working using older version of Nextflow (21.04.3.5560)

My Nextflow version: 22.04.5.5708

**Comment by phue** [comment]
Hi @G-Thomson,

sorry for the late reply, somehow missed this.
It looks like the certificate of the CDN expired, which might be causing this.
@ebirn could you have a look at that?

**Comment by mgollo** [comment]
Hi @G-Thomson,
The certificate for cdn.vbc.ac.at has been renewed. Can you please try again to see if this was causing the issue?

Thanks,
Martin
