### ISSUE TITLE
Error: ch-run[62783]: --set-env: can't open: -w: No such file or directory (ch-run.c:219 2)

### ISSUE THREAD

**Issue by nschan** [Gregor-Mendel-Institute/aradeepopsis#65]
Hi @phue!

I am trying to run aradeepopsis with the current releases of nextflow (23.04.1) and charliecloud (0.32) on biohpc_gen.

This errors with

```
Command exit status:
  1

Command output:
  (empty)

Command error:
  ch-run[62783]: --set-env: can't open: -w: No such file or directory (ch-run.c:219 2)
```

We are able to run aradeepopsis only with a very specific combination of nextflow (22.04.4) and charliecloud (0.27) at the moment, which is somewhat inconvenient.
Do you have any suggestions how to resolve this issue? 

Thanks
Niklas

**Comment by phue** [comment]
Hi Niklas,

Charliecloud `0.32` introduced a breaking change. It's [patched](https://github.com/nextflow-io/nextflow/pull/3956) on nextflow master, but not released yet.
For now, you'll have to use charliecloud older than `0.32`

Cheers,
Patrick
